FROM php:8.1.17-fpm-alpine3.17

ARG PROJECT_ENV

# Nginx
RUN apk add --no-cache nginx
RUN mkdir -p /run/nginx
COPY ./docker/nginx/default_gcp.conf /etc/nginx/http.d/default.conf

# PHP
COPY ./docker/php/php.ini $PHP_INI_DIR/php.ini

RUN apk update \
    && apk add autoconf gcc g++ linux-headers make \
    && docker-php-ext-install pdo_mysql opcache \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && adduser -u 1000 sail -D

# Composer install
COPY --from=composer /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin

WORKDIR /var/www/html

COPY . ./
COPY .env.$PROJECT_ENV ./.env

RUN composer install

ENV HOST 0.0.0.0
EXPOSE 8080

CMD sh ./startup.sh
